name: kelompok_uts
description: "A new Flutter project."

publish_to: 'none' # This prevents the package from being published publicly.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.0.12 # Ditambahkan untuk mendukung fungsi seperti getApplicationDocumentsDirectory
  image_picker: ^0.8.7+3
  flutter_rating_bar: ^4.0.0  # Ditambahkan untuk rating bintang

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img_1.png
    - assets/images.png
    - assets/img_3.png
    - assets/img_4.png
    - assets/img_6.png
    - assets/img_7.png
    - assets/img_8.png
